theme: minima
markdown: kramdown

title: |-
    Learning AI for Dextrous Robots

author: berthold.baeuml@tum.de

social_links:
  - { platform: youtube,  user_url: "https://github.com/aidx-lab/aidx-lab" }

header_pages:
  - _pages/research.md
  - _pages/robot.md
  - _pages/team.md
  - _pages/videos.md


include:
    - _pages
    
exclude: 
    - .gitignore
    - Gemfile
    - README.md
